{% set version = "1.3.1" %}

package:
  name: kiwisolver
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/k/kiwisolver/kiwisolver-{{ version }}.tar.gz
  sha256: 950a199911a8d94683a6b10321f9345d5a3a8433ec58b217ace979e18f16e248

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler("cxx") }}
  host:
    - python
    - pip
    - setuptools
    - cppy
  run:
    - python

test:
  imports:
    - kiwisolver

about:
  home: https://github.com/nucleic/kiwi
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A fast implementation of the Cassowary constraint solver

extra:
  recipe-maintainers:
    - blink1073
    - ericdill
    - licode
    - MatthieuDartiailh
    - sccolbert
    - tacaswell
    - ocefpaf
